allRoles = {
// roles deck
  werewolf_1 : {
    name: 'Werewolf',
    type: 'werewolf',
    index: 0,
    dark: true,
    deck: 'roles',
    fellows: 'werewolf',
    active: 'night',
  },
  werewolf_2 : {
    name: 'Werewolf',
    type: 'werewolf',
    index: 1,
    dark: true,
    deck: 'roles',
    fellows: 'werewolf',
    active: 'night',
  },
  werewolf_3 : {
    name: 'Werewolf',
    type: 'werewolf',
    index: 2,
    dark: true,
    deck: 'roles',
    fellows: 'werewolf',
    active: 'night',
  },
  werewolf_vigilante : {
    name: 'Werewolf Vigilante',
    type: 'werewolf',
    index: 3,
    dark: true,
    deck: 'roles',
    vigilante: true,
    fellows: 'werewolf',
    active: 'night',
  },
  darkVillager : {
    name: 'Dark Villager',
    type: 'darkVillager',
    dark: true,
    deck: 'roles',
    fellows: 'werewolf',
    active: null,
  },
  wolfsbane : {
    name: 'Wolfsbane',
    type: 'wolfsbane',
    dark: false,
    deck: 'roles',
    active: 'night',
  },
  trapper : {
    name: 'Trapper',
    type: 'trapper',
    dark: false,
    deck: 'roles',
    active: 'night',
  },
  seer : {
    name: 'Seer',
    type: 'seer',
    index: 0,
    dark: false,
    deck: 'roles',
    unreliable: false,
    active: 'night',
  },
  seer_unreliable: {
    name: 'Unreliable Seer',
    type: 'seer',
    index: 1,
    dark: false,
    deck: 'roles',
    unreliable: true,
    active: 'night',
  },
  vigilante : {
    name: 'Vigilante',
    type: 'vigilante',
    index: 0,
    dark: false,
    deck: 'roles',
    vigilante: true,
    active: 'day',
  },
  mayor : {
    name: 'Mayor',
    type: 'mayor',
    dark: false,
    deck: 'roles',
    active: null,
    votes: 2,
  },
  cultist_1 : {
    name: 'Cultist',
    type: 'cultist',
    index: 0,
    dark: false,
    deck: 'roles',
    fellows: 'cultist',
    active: null,
  },
  cultist_2 : {
    name: 'Cultist',
    type: 'cultist',
    index: 1,
    dark: false,
    deck: 'roles',
    fellows: 'cultist',
    active: null,
  },
  cultist_3 : {
    name: 'Cultist',
    type: 'cultist',
    index: 2,
    dark: false,
    deck: 'roles',
    fellows: 'cultist',
    active: null,
  },
  cultist_4 : {
    name: 'Cultist',
    type: 'cultist',
    index: 3,
    dark: false,
    deck: 'roles',
    fellows: 'cultist',
    active: null,
  },
// lovers deck
  lovers_1 : {
    name: 'Lover Pair',
    type: 'lovers',
    index: 0,
    deck: 'lovers',
    number: 2,
    fellows: 'lover',
  },
  lovers_2 : {
    name: 'Lover Pair',
    type: 'lovers',
    index: 1,
    deck: 'lovers',
    number: 2,
    fellows: 'lover',
  },
  lovers_triad : {
    name: 'Lover Triad',
    type: 'lovers',
    index: 2,
    deck: 'lovers',
    number: 3,
    fellows: 'lover',
  },
  rivals : {
    name: 'Rival Pair',
    type: 'rivals',
    deck: 'lovers',
    number: 2,
    fellows: 'rival',
  },
};

roleInfo = function (name) {
  return name ? (allRoles[name] || {
    name: 'Ordinary Villager',
    type: 'villager',
    dark: false,
    deck: 'roles',
  }) : {
    name: 'Zombie',
    type: 'zombie',
    dark: false,
    deck: 'roles',
  };
}
